version: '3.8'

services:
  web:
    image: nginx:alpine
    container_name: html-js-server
    ports:
      - "8080:80"
    volumes:
      - ./:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
